# top level stuff you probably don't need to touch
remote_theme: jekyller/sustain
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://easy00.github.io/
baseurl: ""
title: Jiyoung Lee
author: Jiyoung Lee
description: Personal blog and resume
avatar: profile.png
email: easy00@yonsei.ac.kr
github: jekyller/sustain # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
